//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "CNFRegWizardControllerDelegate.h"
#import "IMSystemMonitorListener.h"
#import "UIApplicationDelegate.h"

@class BKSProcessAssertion, CKMessagesController, CNFRegWizardController, NSArray, NSString, NSURL, TLAlert, UIWindow;

@interface SMSApplication : UIApplication <CNFRegWizardControllerDelegate, IMSystemMonitorListener, UIApplicationDelegate>
{
    _Bool _waitToSendFinishLaunching;
    _Bool _isLocked;
    _Bool _isSuspended;
    _Bool _isHandlingSiriTask;
    UIWindow *_window;
    CKMessagesController *_messagesController;
    CNFRegWizardController *_madridRegistrationController;
    NSString *_defaultPng;
    NSArray *_suspendUnreadMessages;
    BKSProcessAssertion *_backgroundAssertion;
    TLAlert *_alert;
    NSURL *_deferredLoadURL;
    CDUnknownBlockType _alertViewHandler;
}

@property(copy, nonatomic) CDUnknownBlockType alertViewHandler; // @synthesize alertViewHandler=_alertViewHandler;
@property(retain, nonatomic) CKMessagesController *messagesController; // @synthesize messagesController=_messagesController;
@property(retain, nonatomic) NSURL *deferredLoadURL; // @synthesize deferredLoadURL=_deferredLoadURL;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)_handleDaemonDisconnected:(id)arg1;
- (void)_handleDaemonConnected:(id)arg1;
- (void)_handleAccountsChanged:(id)arg1;
- (_Bool)_shouldShowMadridRegistrationView;
- (void)firstRunControllerDidFinish:(id)arg1 finished:(_Bool)arg2;
- (void)_updateMadridRegistrationViewAnimated:(_Bool)arg1;
- (void)_destroyMadridRegistrationView;
- (void)_createMadridRegistrationViewIfNecessary;
- (void)_showMadridRegistrationViewIfNecessary;
- (void)__showMadridRegistrationViewIfNecessary;
- (void)_chatItemsDidChange:(id)arg1;
- (void)_updateDefaultPNGSuspended;
- (void)_updateAppSnapshot;
- (void)__updateAppSnapshot;
- (_Bool)_isShowingNewComposition;
- (void)_applicationDidRemoveDeactivationReason:(id)arg1;
- (void)_scheduleDeferredSetup;
- (void)applicationSignificantTimeChange:(id)arg1;
- (_Bool)applicationSuspendWithSettings:(id)arg1;
- (void)systemApplicationDidResumeForEventsOnly;
- (void)systemApplicationDidSuspendForEventsOnly;
- (void)systemApplicationDidResume;
- (void)systemApplicationDidSuspend;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidResumeFromUnderLock;
- (void)_prepareForResume:(_Bool)arg1;
- (void)_prepareForSuspend;
- (_Bool)openURL:(id)arg1;
- (void)reportAppLaunchFinished;
- (void)setWaitToSendFinishLaunching:(_Bool)arg1;
- (void)applicationOpenURL:(id)arg1;
- (_Bool)isLocked;
- (_Bool)isHandlingURL;
- (void)_storeState;
- (_Bool)_restoreState:(out CDUnknownBlockType *)arg1;
- (_Bool)_restoreState;
- (void)handleURL:(id)arg1;
- (void)_activateSiriForRecipient:(id)arg1;
- (void)_activateSiriForConversation:(id)arg1;
- (void)_loadURLMessageGUID:(id)arg1;
- (void)_messageSendFailed:(id)arg1;
- (void)_messageSent:(id)arg1;
- (void)_messageReceived:(id)arg1;
- (void)_resetIdleTimer;
- (void)_playMessageReceivedForMessage:(id)arg1 inChat:(id)arg2;
- (void)_playMessageSent;
- (void)dealloc;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)_application:(id)arg1 handleSiriTask:(id)arg2;
- (id)init;
- (id)defaultPng;
- (void)setDefaultPng:(id)arg1;
- (void)_clearFailureBadge;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

