//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SMSApplication.h"

@interface SMSApplication (mSMSApplicationTesting)
- (void)didChangeOrientation:(id)arg1;
- (void)startPhotoTest:(id)arg1;
- (void)clearEntryView;
- (void)sendSelectedPhotoWithCompletion:(CDUnknownBlockType)arg1;
- (void)selectAPhotoInPickerWithCompletion:(CDUnknownBlockType)arg1;
- (void)dismissPhotoPickerWithCompletion:(CDUnknownBlockType)arg1;
- (void)showPhotoPickerInTranscriptWithCompletion:(CDUnknownBlockType)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)startScrollConversationsTest:(id)arg1;
- (void)startRotationTest:(id)arg1;
- (void)startScrollTranscriptTest:(id)arg1;
- (void)startShowNewComposeTest:(id)arg1;
- (void)startShowMessagesTest:(id)arg1;
- (void)showNextMessage;
- (void)didShowTranscriptList;
- (void)didShowNewCompose;
- (void)didShowAMessage;
- (void)scrollTranscript;
- (void)showKeyboard;
- (void)showTranscriptListNotAnimated;
- (void)showTranscriptList;
- (void)failedTest:(id)arg1;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
@end

